# Generated by Django 4.1 on 2022-09-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_anime_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='watchList',
            field=models.ManyToManyField(blank=True, to='home.anime'),
        ),
    ]
