# Generated by Django 4.1 on 2022-08-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(max_length=2000),
        ),
    ]
