# Generated by Django 4.1 on 2022-08-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_anime_genre_anime_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='home.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='num_of_episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
