# Generated by Django 4.1 on 2022-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_anime_genre_anime_genres_alter_anime_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
