# Generated by Django 4.1 on 2022-09-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_genre_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['-like']},
        ),
    ]
